language: generic 

sudo: required
services:
  docker:

before_install:
  - docker build -t arturryzhyigl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arturryzhyigl/react-test npm test

after_sucess:
  - docker build -t arturryzhyigl/multi-client ./client
  - docker build -t arturryzhyigl/multi-nginx ./nginx
  - docker build -t arturryzhyigl/multi-server ./server
  - docker build -t arturryzhyigl/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arturryzhyigl/multi-client
  - docker push arturryzhyigl/multi-nginx
  - docker push arturryzhyigl/multi-server
  - docker push arturryzhyigl/multi-worker
